### ISSUE TITLE
.sendFileMessage() in React-Native

### ISSUE THREAD

**Issue by iramlg** [smilefam/SendBird-JavaScript#19]
I am implementing a React-Native APP using SendBird, but I couldn't find a way of implementing the .sendFileMessage() inside React-Native. 

Is there any way I could implement that!?

**Comment by iramlg** [comment]
just figured a way, have to make a object with those atributes and pass to the sendFileMessage(), the image in my example is what returns from camera roll so path is relative to the device, hope this helps anyone needing this feature in react native!

'''
let photo = {
    uri: image.path,
    type: image.mime,
    name: image.name,
};

channel.sendFileMessage(photo)
'''

**Comment by pgarciacamou** [comment]
@iramlg I just created [this stackoverflow question](http://stackoverflow.com/questions/42171139/sendbird-send-image-file). 

I'm trying to do the same as you: using react-native with sendbird.

1. Is the `photo` object you created the same as `FILE` in the [JS docs](https://docs.sendbird.com/javascript#open_channel_3_sending_messages).
2. What if you wanted to send an asset instead of an image from the camera roll, would the path be a relative path as well?

**Comment by iramlg** [comment]
@pgarciacamou 

1 - The photo object is the same of FILE, it just mimic the actual object that standard HTML File Input creates for sendbird (and everything else in the internet). Needed to do that since the object that camera roll returns is different.

2 - I belive you will need to test that, but since the asset is in the device it should work. Just check out how to find the asset path.

**Comment by pgarciacamou** [comment]
@iramlg thanks so much! I managed to make it work the same way you did.

Even if the docs specify that you need to send everything separately (FILE, FILE_NAME, etc...), I ended up sending an object (same as you) and it works.

I just had to obtain the image URI like the following:

```jsx
import image from './assets/images/some_image.png';

// ...

<Image
  source={image}
  onLoad={({ nativeEvent }) => {
    // the documentation states that `source` only works on iOS as of today.
    let { source } = nativeEvent;
    let { url } = source;
    let photo = {
      uri: url, // required
      type: 'image/png', // required
      name: 'icon_settings.png', // required
      // size: 3000, // optional => default=0
    };

    channel.sendFileMessage(photo, (message, error) => {
      if(error) {
        // handle error
        return;
      }
      // handle success
    });

  }}
/>
```

**FULL DISCLOSURE: this is just a hard coded example of how I solved the problem, I haven't test it on production. I'm just documenting here to help other people. I will answer the stackoverflow question when I have tested this on production.**

**Comment by iramlg** [comment]
@pgarciacamou , your project still up and running?

Seens something broke the last days with .sendFileMessage() and there is no way I could get this working.

Even did checkout to older commits and versions and still nothing, seens something changed in the endpoint.

**Comment by pgarciacamou** [comment]
@iramlg I've been working on a different thing since my last comment, I will probably test today and let you know.

**Comment by pgarciacamou** [comment]
@iramlg I just had time to test this! It is definitely NOT working anymore and I didn't change anything in the request.

Have you found a solution?

![screen shot 2017-03-01 at 4 04 46 pm](https://cloud.githubusercontent.com/assets/8354571/23487121/e49fcd9c-fe98-11e6-95d7-80926b6f3bbe.png)

**Comment by pgarciacamou** [comment]
@iramlg I fixed it by sending the URI instead of an object.

My guess is they updated the JS API to be compliant with the docs.

before, I was doing as you mentioned:

```jsx
import image from './assets/images/some_image.png';

// ...

<Image
  source={image}
  onLoad={({ nativeEvent }) => {
    // the documentation states that `source` only works on iOS as of today.
    let { source } = nativeEvent;
    let { url } = source;
    let photo = {
      uri: url, // required
      type: 'image/png', // required
      name: 'icon_settings.png', // required
      // size: 3000, // optional => default=0
    };

    channel.sendFileMessage(photo, (message, error) => {
      if(error) {
        // handle error
        return;
      }
      // handle success
    });

  }}
/>
```


now:

```jsx
import image from './assets/images/some_image.png';

// ...

<Image
  source={image}
  onLoad={({ nativeEvent }) => {
    // the documentation states that `source` only works on iOS as of today.
    let { source } = nativeEvent;
    let { url } = source;

    let FILE = url;
    let FILE_NAME = 'icon_settings.png';
    let FILE_TYPE = 'image/png';
    let FILE_SIZE = 0;
    let CUSTOM_DATA = {};

    channel.sendFileMessage(FILE, FILE_NAME, FILE_TYPE, FILE_SIZE, CUSTOM_DATA, (message, error) => {
      if(error) {
        // handle error
        return;
      }
      // handle success
    });

  }}
/>
```


PLEASE test this and let me know if it works for you.

**Comment by sf-jin-ku** [comment]
@pgarciacamou @iramlg Hi! Please download our latest RN sample CODE + sdk. 
We added sample implementation of sending files in React Native.

Thanks!

**Comment by booboothefool** [comment]
Still getting this error on 3.0.26 with both methods mentioned by @pgarciacamou on my Google Pixel.

**Comment by pgarciacamou** [comment]
@booboothefool I'm glad you mentioned that, I'm only testing on iOS devices (I couldn't help you with that).

CC: @sf-jin-ku

**Comment by sf-jin-ku** [comment]
@pgarciacamou @booboothefool We've got a report from other customers who had older version of react-native-cli and had the same problem. Could you update cli util ?

nom install -g react-native-cli

Then delete sample repo for on you local and clone again and then npm install and react-native run-ios or run-android? This should resolve the issue!

**Comment by pgarciacamou** [comment]
@sf-jin-ku I haven't had issues with iOS and react-native. If I encounter any, I'll try that 👍

**Comment by booboothefool** [comment]
@pgarciacamou @sf-jin-ku

Yeah, it works perfectly on iOS. On Android it only seems to only work about half the time, randomly failing with: https://cloud.githubusercontent.com/assets/8354571/23487121/e49fcd9c-fe98-11e6-95d7-80926b6f3bbe.png

**Comment by sf-jin-ku** [comment]
@booboothefool @pgarciacamou

Yeah. We also noticed that.
This is due to a race condition in Image Picker library.
Before you send over file object using sendFileMessage, could you give 100~200ms delay?
Then it should work perfect on Android. ( And in general this issue will happen very rarely in release mode + real device )

Thanks!

**Comment by booboothefool** [comment]
@sf-jin-ku 

I have no idea why that would help, but for some reason it did help a bit...

It still seems a bit too random though. Definitely not "perfect" and still happens a decent amount in release mode + real device. It's like if it fails, and you try again 10 minutes later, you might get lucky and the picture sends.

I think it needs improvement 😞 , but it doesn't really seem like entirely a SendBird issue.

**Comment by sf-jin-ku** [comment]
@booboothefool ah. okay. we might need to move to another libaray. sorry for the issue.
The better workaround would be like this.

This is from https://github.com/marcshilling/react-native-image-picker/issues/254

if (Platform.OS === 'ios') {
        //send file      
} else {
        this.imageCheckInterval = setInterval( () => {         
          Image.getSize(
            response.uri,
            () => {
              clearInterval(this.imageCheckInterval);
              // sendfile
            }
          );
        }, CHECK_IMAGE_URI_INTERVAL_MS);
      }

This one uses "getSize" as a proxy that ensures the file has been created/exist.

Can you try this?

**Comment by booboothefool** [comment]
@sf-jin-ku Wow, that works a lot better!

Perhaps it should be done for iOS as well though because iOS can fail too, although it is extremely rare.

I'm going to go with:
```
        const CHECK_IMAGE_URI_INTERVAL = Platform.OS === 'android' ? 500 : 100;
        this.imageCheckInterval = setInterval(() => {
          // Use getSize as a proxy for when the image exists
          Image.getSize(
            response.uri,
            () => {
              clearInterval(this.imageCheckInterval);
              this.sendPhoto();
            }
          );
        }, CHECK_IMAGE_URI_INTERVAL);
```

Pretty solid though. Thanks!

**Comment by xinlangzi** [comment]
I found this issue still exists. I can't make it work well in android on sendFileMessage. Anyone can help?
