### ISSUE TITLE
Not able to upload image file to sendbird server from local phone storage as new profile image 

### ISSUE THREAD

**Issue by Jacky9425** [smilefam/SendBird-JavaScript#78]
Hi, I am using `sb.updateCurrentUserInfoWithProfileImage` to update the current user's profile image. However, i was only able to change the image and upload it successfully if the image is captured using camera. If i picked an image from my phone's local storage, the API is not working and the image is not uploaded or updated in the sendbird server.  I've compared the parameter with `sb.sendFileMessage`, and both are requiring same type of parameter.

May i know is this a bug on SendBird?

**Comment by Alchemist85K** [comment]
@Jacky9425 
We'll resolve this issue to the next version(v3.0.95).
Thank you for your interest in SendBird SDK :)

**Comment by Jacky9425** [comment]
Hi, the same problem occurs on` sb.GroupChannel.createChannelWithUserIds(userIds, true, this.state.newGroupName, ../images/sample.jpg, null, null, function(channel, error)` where the path is the image file i saved in my project's directory. If i put the directory path, the code does not returns error but the channel is created without uploading the image file. However if i put in a string that is a web url containing an image file, the image is uploaded successfully.

**Comment by Alchemist85K** [comment]
@Jacky9425 
I'm so sorry. The function is missing. I'll deploy a new version fixed this issue.

**Comment by Alchemist85K** [comment]
@Jacky9425 
I deployed a new version(3.0.96) which was fixed this issue.

**Comment by Jacky9425** [comment]
May i know which function is missing?

**Comment by Jacky9425** [comment]
Hi, i still get the same error when updating the profile image of user (using function `updateCurrentUserInfoWithProfileImage `). This is the error i got : {name: "SendBirdException", code: 800220, message: "Request failed."}

**Comment by Alchemist85K** [comment]
The meaning of "the function is missing" was that the bug-fixed function was not included in the v3.0.95 SDK. So, I deployed v3.0.96 including the bug-fixed function.

That error appears when the file upload fails.
Are you developing it on React Native? What platform is it?
Could you show me the part of the code you wrote?

**Comment by Jacky9425** [comment]
yes it is developed on React Native.

update profile function:
```
_onUpdateProfile() {
        var sb = SendBird.getInstance();
        var _Self = this;

        // can upload camera photo
        sb.updateCurrentUserInfoWithProfileImage(_Self.state.nickname, imgSource, (user, error) => {
            if (error){
                console.log(error);
                return;
            }
            this.props.navigator.pop({refresh: _Self.props.route.refresh});
        })
    }
```

this is the function of react-native-image-picker to capture the image file to be used.
```
    _changeProfileImg(){
        var _Self = this;

        if (Platform.OS === 'android'){
            sb.disableStateChange();
        }

        ImagePicker.showImagePicker(options, (response) => {

            console.log(options.chooseFromLibraryButtonTitle);

            if (Platform.OS === 'android'){
                sb.enableStateChange();
            }

            if (response.didCancel){
                console.log('user cancelled image picker');
            }
            else if (response.error){
                console.log('imagePicker error', response.error);
            }
            else if (response.customButton){
                console.log('customised clicked', response.customButton);
            }
            else{
                let source = {uri:response.uri};
                console.log('SOURCE',source);
                
                if(response.name){
                    source['name'] = response.fileName
                } else {
                    paths = response.uri.split("/")
                    source['name'] = paths [paths.length-1];
                }

                if(response.type){
                    source['type'] = response.type;
                }
                
                this.setState({
                    profileUrl: response.uri,
                });

                const CHECK_INTERVAL = Platform.OS === 'android' ? 300 : 100;

                setTimeout(() => {
                    Image.getSize(response.uri,
                        () => {
                            imgSource = source;
                            console.log('cameraphoto',imgSource);
                        })
                }, CHECK_INTERVAL);
            }
        });
    }
```

**Comment by Alchemist85K** [comment]
We provide a React Native Sample that is created using "react-native-image-picker".
It doesn't use "updateCurrentUserInfowithProfileImage()", but it'll be a good reference.(https://github.com/smilefam/SendBird-JavaScript/tree/master/react-native-redux-sample)

We reproduced your error. And we found out the issue is not SendBird JavaScript SDK, but React Native Android.
In the same code, iOS succeeds and Android fails.
I think the cause is a "content uri". The relevant information is on StackOverflow. Could you check this link?
Link: https://stackoverflow.com/questions/36259339/convert-content-uri-to-actual-path-for-android-using-react-native

**Comment by Jacky9425** [comment]
okay, will look into it. Thanks for pointing out its an android issue because i only able to test the app on android based only.

**Comment by Jacky9425** [comment]
Hi, does the same reason applies on changing coverUrl of channels? Because i am trying to fix the coverUrl to a certain logo rather than using the randomly generated images. But the same issue when i try to upload an image from my project directory. Works fine if i put in a string of url that points to certain image.

**Comment by Alchemist85K** [comment]
If you try to use updateChannel with File, you'll get the error.
So, we're going to resolve this issue.

**Comment by Alchemist85K** [comment]
@Jacky9425 

I'm sorry I'm late.
We released JavaScript SDK which fixed this issue. 
Could you check with the latest version(v3.0.97)? 

Thank you for your interest in SendBird SDK. :)
